name: Cypress Tests

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  cypress-run:
    runs-on: self-hosted

    steps:
      # 1️⃣ Checkout
      - uses: actions/checkout@v4

      # 2️⃣ Node
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3️⃣ Install deps
      - run: npm ci

      # 4️⃣ Run Cypress
      - name: Run Cypress
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_user: ${{ secrets.CYPRESS_USER_GHA }}
          CYPRESS_pass: ${{ secrets.CYPRESS_PASS_GHA }}
        with:
          browser: chrome

      # 5️⃣ Install Allure
      - name: Install Allure
        if: always()
        run: npm install -g allure-commandline

      # 6️⃣ Fix Allure executor (REMOVE Jenkins)
      - name: Set Allure executor
        if: always()
        shell: powershell
        run: |
          if (!(Test-Path allure-results)) {
            New-Item -ItemType Directory -Path allure-results
          }

          if (Test-Path allure-results\executor.json) {
            Remove-Item -Force allure-results\executor.json
          }

          $json = '{ "name": "GitHub Actions", "type": "ci", "buildName": "Run #${{ github.run_number }}", "buildUrl": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}", "reportUrl": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" }'
          $json | Out-File -Encoding utf8 allure-results\executor.json

      # 7️⃣ Generate Allure report
      - name: Generate Allure report
        if: always()
        run: allure generate allure-results --clean -o allure-report

      # 8️⃣ Deploy to GitHub Pages
      - name: Deploy Allure to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: allure-report