name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2] # Puedes ajustar el número de contenedores para más paralelismo

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Cypress tests (record to Cloud)
        uses: cypress-io/github-action@v6
        with:
          command: npx cypress run    # Ejecuta los tests directamente (sin npm start)
          record: true                # Graba resultados en Cypress Cloud
          parallel: true              # Ejecuta en paralelo
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
